theme: jekyll-theme-cayman
title: Morphy
description: Morphological phylogenetics accommodating inapplicable data
github:
    is_project_page: false
    about_url: http://www.morphyproject.org
    downloads_url: http://www.morphyproject.org/download.html
    user_guide_url: http://www.morphyproject.org/userguide.html
    fxnlib_url: http://www.morphyproject.org/fxnlib.html
    faq_url: http://www.morphyproject.org/faq.html

google_analytics: UA-174923171-1
